name: Build and Deploy VuePress Site

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Install VuePress
      - name: Install VuePress
        run: npm install -D vuepress@next && npm i @vuepress/cli && npm install -g vuepress

      # # Create a VuePress site
      # - name: Create VuePress site
      #   run: vuepress init docs

      # Install necessary packages
      - name: Install necessary packages
        run: npm i stylus && npm i vuepress-plugin-md-enhance && npm i vuepress-theme-bcc-common-components && npm i tailwindcss

      # Setup the right theme config.
      - name: List folders
        run: |
          ls

      - name: Navigate to multiple subfolders
        run: |
          cd docs
          ls
          mkdir .vuepress
          cd .vuepress
          echo "const foo = 'bar';" >> config.js
          echo "console.log(foo);" >> config.js
          echo "import { defineUserConfig } from "vuepress";" >> config.js
          echo "import { getDirname } from "@vuepress/utils";" >> config.js
          echo "import { mdEnhancePlugin } from "vuepress-plugin-md-enhance";" >> config.js
          echo "import { bccCustomTheme } from "vuepress-theme-bcc-common-components/config.js";" >> config.js
          echo "import { findPathIcons } from "vuepress-theme-bcc-common-components/helpers/findPathIcons.js";" >> config.js
          echo "import { getSideBarItems } from "vuepress-theme-bcc-common-components/helpers/getSidebarItems.js";" >> config.js
          echo "const __dirname = getDirname(import.meta.url);" >> config.js
          cat config.js

      # Build the VuePress site
      - name: Build VuePress site
        run: vuepress build docs

      # Deploy the built site as an asset to the repository
      - name: Deploy built site
        uses: actions/upload-artifact@v1
        with:
          name: vuepress-site
          path: docs/.vuepress/dist
